### PR TITLE
added a test that asserts true to test/models/user_test.rb. 

### PR DESCRIPTION
**Pull request by shaunshapiro**
Also commented out lines in test/fixtures/users.yml (generated from scaffolding) as it causes an error when running rake.

### CODE REVIEW

**Comment by shaunshapiro** [comment]
Hey Jeff what do you think of this? It's a really simple edit but just wanted some feedback so I can go ahead and merge it.

**Comment by johnnyiller** [comment]
Yeah go ahead.  No issue as far as I can tell.

**Comment by cryogenx** [comment]
went ahead and merged it in so we can get to work on other things!

**Comment by shaunshapiro** [comment]
Thanks @cryogenx !

**Comment by cryogenx** [comment]
anytime!

**Pull request merged**
